name: Auto PR and Merge to deploy
'on':
  push:
    branches:
      - feature
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]

jobs:
  test-and-create-pr:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        # Replace with your build and test commands
        ./gradlew build test

    - name: Create PR
      run: |
        gh pr create --base develop --head ${{ github.ref }} --title "Automated PR from ${{ github.ref }}" --body "Tests passed on feature branch. Ready for merge."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-and-merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and test
      run: |
        # Replace with your build and test commands
        ./gradlew build test

    - name: Merge PR
      if: success()
      run: gh pr merge ${{ github.event.pull_request.number }} --merge
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
