name: Auto PR and Merge to deploy
'on':
  push:
    branches:
      - feature
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build and run unit tests
        run: |
          ./gradlew checkstyleMain
          ./gradlew checkstyleTest
          ./gradlew checkstyleIntegrationTest
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Build and run unit tests
        run: |
          chmod +x gradlew
          ./gradlew build
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Run application
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          java -jar build/libs/imaginarium-0.0.1-SNAPSHOT.jar &
          ./gradlew integrationTest
  system-tests:
    runs-on: ubuntu-latest
    needs:
      - checkstyle
      - unit-tests
      - integration-tests
    steps:
      - uses: actions/checkout@v3
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin
      - name: Run application
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          java -jar build/libs/imaginarium-0.0.1-SNAPSHOT.jar &
          ./gradlew systemTest
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: >
            ${{ github.workspace
            }}/**/build/reports/jacoco/prodNormalDebugCoverage/prodNormalDebugCoverage.xml,

            ${{ github.workspace }}/**/build/reports/jacoco/**/debugCoverage.xml
          token: '${{ secrets.GITHUB_TOKEN }}'
          min-coverage-overall: 40
          min-coverage-changed-files: 60
  test-and-merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: |
          # Replace with your build and test commands
          ./gradlew build test
      - name: Merge PR
        if: success()
        run: 'gh pr merge ${{ github.event.pull_request.number }} --merge'
        env:
          GH_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
