name: 'Build and run tests'

on:
  push:
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ...
      - name: Build and run unit tests
        run: |
          ./gradlew checkstyleMain
          ./gradlew checkstyleTest
          ./gradlew checkstyleIntegrationTest

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      ...
      - name: Build and run unit tests
        run: |
          chmod +x gradlew
          ./gradlew build

  integration-tests:
    runs-on: ubuntu-latest
    needs: [checkstyle, unit-tests]
    steps:
      - uses: actions/checkout@v3
      ...
      - name: Run Integration Tests
        run: |
          chmod +x gradlew
          ./gradlew integrationTest

  system-tests:
    runs-on: ubuntu-latest
    needs: [checkstyle, unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v3
      ...
      - name: Run application
        run: |
          chmod +x gradlew
          ./gradlew bootJar
          java -jar build/libs/imaginarium-0.0.1-SNAPSHOT.jar &
      - name: Wait for application to start
        run: sleep 30  
      - name: Execute System Tests
        run: ./gradlew systemTest
      - name: Cleanup
        run: pkill -f imaginarium-0.0.1-SNAPSHOT.jar  
